version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - pwd
      - cd lambda/prevalidate
      - zip -j lambda Handler.py ../../load/PreValidate.py ../../load/LPTSExtractReader.py ../../load/PreValidateResult.py ../../load/UnicodeScript.py   ../../load/TextStockNumberProcessor.py ../../load/LanguageReaderCreator.py  ../../load/LanguageReader.py ../../load/StageCLanguageReader.py
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing lambda function update... 
      - aws lambda update-function-code --function-name $FUNCTION_NAME  --zip-file fileb://./lambda.zip