default:
	zip -j  prevalidate_lambda Handler.py ../../load/PreValidate.py ../../load/LPTSExtractReader.py ../../load/UnicodeScript.py   ../../load/TextStockNumberProcessor.py ../../load/PreValidateResult.py

clean:
	rm prevalidate_lambda.zip