default:
	zip -j  prevalidate_lambda Handler.py ../../load/PreValidate.py ../../load/LPTSExtractReader.py ../../load/PreValidateResult.py ../../load/UnicodeScript.py   ../../load/TextStockNumberProcessor.py ../../load/LanguageReaderCreator.py  ../../load/LanguageReader.py ../../load/StageCLanguageReader.py

clean:
	rm prevalidate_lambda.zip