version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - pwd
      - cd lambda/databasecheck
      - sh ../generate-dbp-etl-cfg.sh
      - zip -j lambda dbp-etl.cfg Handler.py ../../load/Config.py ../../load/DatabaseCheck.py ../../load/LPTSExtractReader.py  ../../load/LanguageReaderCreator.py  ../../load/LanguageReader.py ../../load/SQLUtility.py
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing lambda function update... 
      - aws lambda update-function-code --function-name $FUNCTION_NAME  --zip-file fileb://./lambda.zip