-- DBP Views --

CREATE VIEW `access_group_filesets_view` AS select `bf`.`id` AS `fileset_id`,`bf`.`asset_id` AS `asset_id`,`bf`.`set_type_code` AS `set_type_code`,`bf`.`hash_id` AS `hash_id`,`agf`.`access_group_id` AS `access_group_id` from (`bible_filesets` `bf` join `access_group_filesets` `agf`) where (`bf`.`hash_id` = `agf`.`hash_id`);

CREATE VIEW `bible_file_tags_view` AS select `bf`.`id` AS `fileset_id`,`bf`.`asset_id` AS `asset_id`,`bf`.`set_type_code` AS `set_type_code`,`bf`.`hash_id` AS `hash_id`,`bft`.`file_id` AS `file_id`,`bft`.`tag` AS `tag`,`bft`.`value` AS `value`,`bft`.`admin_only` AS `admin_only` from ((`bible_filesets` `bf` join `bible_files` `bf2`) join `bible_file_tags` `bft`) where ((`bf`.`hash_id` = `bf2`.`hash_id`) and (`bft`.`file_id` = `bf2`.`id`));

CREATE VIEW `bible_file_stream_bandwidths_view` AS select `bf`.`id` AS `fileset_id`,`bf`.`asset_id` AS `asset_id`,`bf`.`set_type_code` AS `set_type_code`,`bf`.`hash_id` AS `hash_id`,`bf2`.`id` AS `file_id`,`bfvr`.`file_name` AS `file_name`,`bfvr`.`bandwidth` AS `bandwidth`,`bfvr`.`resolution_width` AS `resolution_width`,`bfvr`.`resolution_height` AS `resolution_height`,`bfvr`.`codec` AS `codec`,`bfvr`.`stream` AS `stream` from ((`bible_filesets` `bf` join `bible_files` `bf2`) join `bible_file_stream_bandwidths` `bfvr`) where ((`bf`.`hash_id` = `bf2`.`hash_id`) and (`bf2`.`id` = `bfvr`.`bible_file_id`));

CREATE VIEW `bible_file_stream_ts_view` AS select `bf`.`id` AS `fileset_id`,`bf`.`asset_id` AS `asset_id`,`bf`.`set_type_code` AS `set_type_code`,`bf`.`hash_id` AS `hash_id`,`bf2`.`id` AS `file_id`,`bfvts`.`stream_bandwidth_id` AS `stream_bandwidth_id`,`bfvts`.`file_name` AS `file_name`,`bfvts`.`runtime` AS `runtime` from (((`bible_filesets` `bf` join `bible_files` `bf2`) join `bible_file_stream_bandwidths` `bfvr`) join `bible_file_stream_ts` `bfvts`) where ((`bf`.`hash_id` = `bf2`.`hash_id`) and (`bf2`.`id` = `bfvr`.`bible_file_id`) and (`bfvr`.`id` = `bfvts`.`stream_bandwidth_id`));

CREATE VIEW `bible_files_view` AS select `bf`.`id` AS `fileset_id`,`bf`.`asset_id` AS `asset_id`,`bf`.`set_type_code` AS `set_type_code`,`bf`.`hash_id` AS `hash_id`,`bf2`.`book_id` AS `book_id`,`bf2`.`chapter_start` AS `chapter_start`,`bf2`.`chapter_end` AS `chapter_end`,`bf2`.`verse_start` AS `verse_start`,`bf2`.`verse_end` AS `verse_end`,`bf2`.`file_name` AS `file_name`,`bf2`.`file_size` AS `file_size`,`bf2`.`duration` AS `duration` from (`bible_filesets` `bf` join `bible_files` `bf2`) where (`bf`.`hash_id` = `bf2`.`hash_id`);

CREATE VIEW `bible_fileset_copyright_organizations_view` AS select `bf`.`id` AS `fileset_id`,`bf`.`asset_id` AS `asset_id`,`bf`.`set_type_code` AS `set_type_code`,`bf`.`hash_id` AS `hash_id`,`bfco`.`organization_id` AS `organization_id`,`bfco`.`organization_role` AS `organization_role` from (`bible_filesets` `bf` join `bible_fileset_copyright_organizations` `bfco`) where (`bf`.`hash_id` = `bfco`.`hash_id`);

CREATE VIEW `bible_fileset_copyrights_view` AS select `bf`.`id` AS `fileset_id`,`bf`.`asset_id` AS `asset_id`,`bf`.`set_type_code` AS `set_type_code`,`bf`.`hash_id` AS `hash_id`,`bfc`.`copyright_date` AS `copyright_date`,`bfc`.`copyright` AS `copyright`,`bfc`.`copyright_description` AS `copyright_description`,`bfc`.`open_access` AS `open_access` from (`bible_filesets` `bf` join `bible_fileset_copyrights` `bfc`) where (`bf`.`hash_id` = `bfc`.`hash_id`);

CREATE VIEW `bible_fileset_tags_view` AS select `bf`.`id` AS `fileset_id`,`bf`.`asset_id` AS `asset_id`,`bf`.`set_type_code` AS `set_type_code`,`bf`.`hash_id` AS `hash_id`,`bft`.`name` AS `name`,`bft`.`description` AS `description`,`bft`.`admin_only` AS `admin_only`,`bft`.`notes` AS `notes`,`bft`.`iso` AS `iso`,`bft`.`language_id` AS `language_id` from (`bible_filesets` `bf` join `bible_fileset_tags` `bft`) where (`bf`.`hash_id` = `bft`.`hash_id`);

CREATE VIEW `bible_filesets_view` AS select `bible_filesets`.`id` AS `fileset_id`,`bible_filesets`.`hash_id` AS `hash_id`,`bible_filesets`.`asset_id` AS `asset_id`,`bible_filesets`.`set_type_code` AS `set_type_code`,`bible_filesets`.`set_size_code` AS `set_size_code`,`bible_filesets`.`hidden` AS `hidden` from `bible_filesets`;

CREATE VIEW `bibles_view` AS select `bf`.`id` AS `fileset_id`,`b`.`id` AS `bible_id`,`b`.`language_id` AS `language_id`,`b`.`versification` AS `versification`,`b`.`numeral_system_id` AS `numeral_system_id`,`b`.`date` AS `date`,`b`.`scope` AS `scope`,`b`.`script` AS `script`,`b`.`derived` AS `derived`,`b`.`copyright` AS `copyright`,`b`.`priority` AS `priority`,`b`.`reviewed` AS `reviewed`,`b`.`notes` AS `notes` from ((`bibles` `b` join `bible_filesets` `bf`) join `bible_fileset_connections` `bfc`) where ((`b`.`id` = `bfc`.`bible_id`) and (`bfc`.`hash_id` = `bf`.`hash_id`));

